import '@/styles/nosotros.css';


export const metadata = {
    title: "Nosotros",
    description: " destacadosGenerated by create next app",
};

export default function Nosotros() {

    return (
        <section className="holder">
            <div className="historia">
                <h2>Historia </h2>
                <div>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium, ut aperiam suscipit, ad asperiores quia, sint porro facilis illo omnis perspiciatis ab obcaecati laudantium sapiente iure. Voluptatum dolore optio vel.</p>

                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium, ut aperiam suscipit, ad asperiores quia, sint porro facilis illo omnis perspiciatis ab obcaecati laudantium sapiente iure. Voluptatum dolore optio vel.</p>

                </div>

            </div>
            <h2>Staff</h2>
            <div className="personas">

                <div className="persona" >
                    <img src="https://fakeimg.pl/120x120" width="75" alt="" />
                    <h5>Juan Gomez</h5>
                    <h6>Gerente General</h6>
                    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus incidunt culpa consectetur nisi quis sapiente asperiores eos odio impedit fugit provident quod quam repudiandae temporibus voluptatibus dolor, saepe rem accusamus.</p>
                </div>

                <div className="persona" >
                    <img src="https://fakeimg.pl/120x120" width="75" alt="" />
                    <h5>Juan Gomez</h5>
                    <h6>Gerente General</h6>
                    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus incidunt culpa consectetur nisi quis sapiente asperiores eos odio impedit fugit provident quod quam repudiandae temporibus voluptatibus dolor, saepe rem accusamus.</p>
                </div>

                <div className="persona" >
                    <img src="https://fakeimg.pl/120x120" width="75" alt="" />
                    <h5>Juan Gomez</h5>
                    <h6>Gerente General</h6>
                    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus incidunt culpa consectetur nisi quis sapiente asperiores eos odio impedit fugit provident quod quam repudiandae temporibus voluptatibus dolor, saepe rem accusamus.</p>
                </div>

                <div className="persona" >
                    <img src="https://fakeimg.pl/120x120" width="75" alt="" />
                    <h5>Juan Gomez</h5>
                    <h6>Gerente General</h6>
                    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus incidunt culpa consectetur nisi quis sapiente asperiores eos odio impedit fugit provident quod quam repudiandae temporibus voluptatibus dolor, saepe rem accusamus.</p>
                </div>

                <div className="persona" >
                    <img src="https://fakeimg.pl/120x120" width="75" alt="" />
                    <h5>Juan Gomez</h5>
                    <h6>Gerente General</h6>
                    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus incidunt culpa consectetur nisi quis sapiente asperiores eos odio impedit fugit provident quod quam repudiandae temporibus voluptatibus dolor, saepe rem accusamus.</p>
                </div>
            </div>
        </section>
    )

}
