import "@/styles/globals.css";

import Nav from "@/components/Nav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <div className="holder">
            <div className="logo">
              <img src="/images/logo.png" width="100" alt="Transportes X" />
              <h1>Transportes X</h1>
            </div>
          </div>
        </header>
        <Nav />

        {children}

        <footer>
          <p>Derechos reservados. Transportes X Año</p>
        </footer>
      </body>

    </html>
  );
}
