import NovedadItem from "@/components/NovedadItem";

export const metadata = {
    title: "Novedades",
    description: " destacadosGenerated by create next app",
};

export default async function Novedades() {

    const data = await fetch(`${process.env.REACT_APP_API_URL}/api/novedades`);
    const novedades = await data.json();
    
    return (
        <section className="holder">
            <h2>Novedades</h2>
            {
                novedades.map(item => <NovedadItem key={item.id}
                    title={item.titulo} subtitle={item.subtitulo}
                    imagen={item.imagen} body={item.cuerpo} />)
            }
        </section>
    )

}
